### ISSUE TITLE
django.conf.urls patterns() removed in django 1.10

### ISSUE THREAD

**Issue by racitup** [jrief/djangoshop-stripe#2]
Hi just trying using django-shop with django 1.10 and got the error:

> File "/Users/rich/.pyenv/versions/3.5.2/lib/python3.5/site-packages/shop_stripe/payment.py", line 7, in <module>
>     from django.conf.urls import patterns
> ImportError: cannot import name 'patterns'

This can be fixed (I think) by returning an empty list from get_urls(self) and removing the import:

> --from django.conf.urls import patterns
> 
> --        return patterns('')
> ++        return []

Thanks for the great work on django shop by the way!
This is my first website so struggling at the moment, but from what I've seen (the requirements list) it looks very comprehensive!

**Comment by jrief** [comment]
This has been fixed in version 0.2.0.
Thanks for reporting.
