### ISSUE TITLE
Docs are incomplete?

### ISSUE THREAD

**Issue by rfleschenberg** [jrief/djangoshop-stripe#3]
To get djangoshop-stripe working, I had to create `myproject/templates/myproject/checkout/payment-method-form.html` with the following content:

```
<form shop-dialog-form name="{{ payment_method_form.form_name }}" novalidate>
	{{ payment_method_form.as_div }}
</form>
{% if payment_modifiers.stripe_payment %}
	{% include "myproject/checkout/stripe-creditcard-form.html" %}
{% endif %}
```

Also, `djangoshop-stripe` must be added to `INSTALLED_APPS`.

We must update the docs.

**Comment by jrief** [comment]
To prevent future users of django-SHOP running into the same problem, his HTML snippet now is part of the original template ``shop/checkout/payment-method-form.html``.

The docs already state:

```
Add ``'shop_stripe'`` to ``INSTALLED_APPS``.
```

**Comment by rfleschenberg** [comment]
I think we should still update the README for `djangoshop-stripe`, to help users who are not running the latest `django-shop` version.
