### ISSUE TITLE
Localization problem

### ISSUE THREAD

**Issue by rfleschenberg** [jrief/djangoshop-stripe#4]
When trying to post the stripe form, I run into this error:

`The 'exp_year' parameter should be an integer (instead, is 2,017).`

We should tell Django not to localize that value.

**Comment by jrief** [comment]
Isn't that implemented as select box?

**Comment by rfleschenberg** [comment]
Yes, but the option value may get localized, so you end up with `2,017` instead of `2017` (see the related PR).
